import { ApiProperty } from "@nestjs/swagger";
import { Type } from "class-transformer";
import {
  IsDateString,
  IsEnum,
  IsNumber,
  IsOptional,
  IsString,
  Min,
} from "class-validator";
import {
  PenaltyReasonType,
  PenaltyStatus,
} from "../entities/penalty.entity";

export class CreatePenaltyDto {
  @ApiProperty({ example: 1 })
  @Type(() => Number)
  @IsNumber()
  @Min(1)
  userId: number;

  @ApiProperty({ example: 100000 })
  @Type(() => Number)
  @IsNumber()
  @Min(0)
  amount: number;

  @ApiProperty({ example: "Kechikkanligi uchun" })
  @IsString()
  reason: string;

  @ApiProperty({ enum: PenaltyReasonType, example: PenaltyReasonType.MANUAL })
  @IsEnum(PenaltyReasonType)
  reasonType: PenaltyReasonType;

  @ApiProperty({ example: "2026-03-14" })
  @IsDateString()
  penaltyDate: string;

  @ApiProperty({ enum: PenaltyStatus, required: false })
  @IsOptional()
  @IsEnum(PenaltyStatus)
  status?: PenaltyStatus;

  @ApiProperty({ required: false, example: false })
  @IsOptional()
  autoGenerated?: boolean;

  @ApiProperty({ required: false, example: "Admin izohi" })
  @IsOptional()
  @IsString()
  adminComment?: string;
}
