import {
  ConflictException,
  Injectable,
  NotFoundException,
} from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import { Repository } from "typeorm";
import dayjs from "dayjs";
import customParseFormat from "dayjs/plugin/customParseFormat";

import { Attendance } from "./entities/attendance.entity";
import { User } from "../users/entities/user.entity";
import { UserRole } from "../users/entities/user-role.enum";
import { PenaltyReasonType } from "../penalties/entities/penalty.entity";
import { CheckInDto } from "./dto/check-in.dto";
import { CheckOutDto } from "./dto/check-out.dto";
import { PenaltiesService } from "../penalties/penalties.service";
import { Settings } from "src/settings/entities/setting.entity";
import { DailyFactsService } from "../daily-facts/daily-facts.service"; 

dayjs.extend(customParseFormat);

@Injectable()
export class AttendanceService {
  constructor(
    private readonly dailyFactsService: DailyFactsService,
    @InjectRepository(Attendance)
    private readonly attendanceRepo: Repository<Attendance>,

    @InjectRepository(User)
    private readonly userRepo: Repository<User>,

    @InjectRepository(Settings)
    private readonly settingsRepo: Repository<Settings>,

    private readonly penaltiesService: PenaltiesService
  ) {}

  private async getSettings() {
    let settings = await this.settingsRepo.findOne({
      where: { id: 1 },
    });

    if (!settings) {
      settings = this.settingsRepo.create({
        id: 1,
        workStartTime: "10:00:00",
        defaultPenaltyAmount: 100000,
        repeatedPenaltyIncrease: 50000,
      });

      settings = await this.settingsRepo.save(settings);
    }

    return settings;
  }

  private getTodayDate() {
    return dayjs().format("YYYY-MM-DD");
  }

  private getNowTime() {
    return dayjs().format("HH:mm:ss");
  }

  private calculateLateMinutes(workStartTime: string, actualTime: string) {
    const start = dayjs(workStartTime, "HH:mm:ss");
    const actual = dayjs(actualTime, "HH:mm:ss");

    if (actual.isBefore(start) || actual.isSame(start)) {
      return 0;
    }

    return actual.diff(start, "minute");
  }

  private async findManagerUser(userId: number) {
    const user = await this.userRepo.findOne({
      where: { id: userId, role: UserRole.MANAGER },
    });

    if (!user) {
      throw new NotFoundException("Manager user topilmadi");
    }

    return user;
  }

  async checkIn(dto: CheckInDto, imageName?: string) {
    const user = await this.findManagerUser(dto.userId);
    const today = this.getTodayDate();

    const existing = await this.attendanceRepo.findOne({
      where: {
        user: { id: dto.userId },
        date: today,
      },
    });

    if (existing?.checkInTime) {
      throw new ConflictException("Bu user bugun allaqachon kelgan");
    }

    const settings = await this.getSettings();
    const nowTime = this.getNowTime();

    const workStartTime =
      user.customStartTime || settings.workStartTime || "10:00:00";

    const lateMinutes = this.calculateLateMinutes(workStartTime, nowTime);
    const late = lateMinutes > 0;

    let attendance = existing;

    if (!attendance) {
      attendance = this.attendanceRepo.create({
        user,
        date: today,
      });
    }

    attendance.checkInTime = nowTime;
    attendance.checkInImage = imageName || null;
    attendance.late = late;
    attendance.lateMinutes = lateMinutes;

    const saved = await this.attendanceRepo.save(attendance);

    if (late && !saved.penaltyCreated) {
      await this.penaltiesService.create({
        userId: user.id,
        amount: Number(settings.defaultPenaltyAmount),
        reason: `Kechikkanligi uchun (${lateMinutes} daqiqa)`,
        reasonType: PenaltyReasonType.LATE,
        penaltyDate: today,
        autoGenerated: true,
      });

      saved.penaltyCreated = true;
      await this.attendanceRepo.save(saved);
    }

    return saved;
  }

  async checkOut(dto: CheckOutDto, imageName?: string) {
  await this.findManagerUser(dto.userId);

  const today = this.getTodayDate();

  const attendance = await this.attendanceRepo.findOne({
    where: {
      user: { id: dto.userId },
      date: today,
    },
  });

  if (!attendance) {
    throw new NotFoundException("Bu user bugun hali kelmagan");
  }

  if (!attendance.checkInTime) {
    throw new ConflictException("User hali check-in qilmagan");
  }

  if (attendance.checkOutTime) {
    throw new ConflictException("Bu user bugun allaqachon ketgan");
  }

  const hasFact = await this.dailyFactsService.hasFactForDate(dto.userId, today);

  if (!hasFact) {
    throw new ConflictException(
      "Ketishdan oldin bugungi fact yozilishi kerak"
    );
  }

  attendance.checkOutTime = this.getNowTime();
  attendance.checkOutImage = imageName || null;

  return await this.attendanceRepo.save(attendance);
}
  async findAll() {
    return await this.attendanceRepo.find({
      order: { createdAt: "DESC" },
    });
  }

  async findByDate(date: string) {
    return await this.attendanceRepo.find({
      where: { date },
      order: { createdAt: "DESC" },
    });
  }

  async findByUser(userId: number) {
    return await this.attendanceRepo.find({
      where: {
        user: { id: userId },
      },
      order: { createdAt: "DESC" },
    });
  }

  async findMine(userId: number) {
    return await this.attendanceRepo.find({
      where: {
        user: { id: userId },
      },
      order: { createdAt: "DESC" },
    });
  }
}