import {
  Column,
  CreateDateColumn,
  Entity,
  ManyToOne,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from "typeorm";
import { User } from "../../users/entities/user.entity";

export enum PenaltyReasonType {
  LATE = "late",
  MANUAL = "manual",
  PLAN_WARNING = "plan_warning",
}

export enum PenaltyStatus {
  PENDING = "pending",
  DONE = "done",
  NOT_DONE = "not_done",
}

@Entity("penalties")
export class Penalty {
  @PrimaryGeneratedColumn()
  id: number;

  @ManyToOne(() => User, { eager: true, onDelete: "CASCADE" })
  user: User;

  @Column("decimal", { precision: 12, scale: 2, default: 0 })
  amount: number;

  @Column()
  reason: string;

  @Column({
    type: "enum",
    enum: PenaltyReasonType,
    default: PenaltyReasonType.MANUAL,
  })
  reasonType: PenaltyReasonType;

  @Column({
    type: "enum",
    enum: PenaltyStatus,
    default: PenaltyStatus.PENDING,
  })
  status: PenaltyStatus;

  @Column({ type: "date" })
  penaltyDate: string;

  @Column({ default: false })
  autoGenerated: boolean;

  @Column({ type: "text", nullable: true })
adminComment: string | null;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}