import { Injectable, NotFoundException } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import { Repository } from "typeorm";
import { Penalty } from "./entities/penalty.entity";
import { CreatePenaltyDto } from "./dto/create-penalty.dto";
import { UpdatePenaltyDto } from "./dto/update-penalty.dto";
import { User } from "../users/entities/user.entity";
import { UserRole } from "../users/entities/user-role.enum";

@Injectable()
export class PenaltiesService {
  constructor(
    @InjectRepository(Penalty)
    private readonly penaltyRepo: Repository<Penalty>,

    @InjectRepository(User)
    private readonly userRepo: Repository<User>
  ) {}

  private async findManagerUser(userId: number) {
    const user = await this.userRepo.findOne({
      where: { id: userId, role: UserRole.MANAGER },
    });

    if (!user) {
      throw new NotFoundException("Manager user topilmadi");
    }

    return user;
  }

  async create(dto: CreatePenaltyDto) {
    const user = await this.findManagerUser(dto.userId);

    const penalty = this.penaltyRepo.create({
      user,
      amount: dto.amount,
      reason: dto.reason,
      reasonType: dto.reasonType,
      penaltyDate: dto.penaltyDate,
      status: dto.status,
      autoGenerated: dto.autoGenerated ?? false,
      adminComment: dto.adminComment ?? null,
    });

    return await this.penaltyRepo.save(penalty);
  }

  async findAll() {
    return await this.penaltyRepo.find({
      order: { createdAt: "DESC" },
    });
  }

  async findOne(id: number) {
    const penalty = await this.penaltyRepo.findOne({
      where: { id },
    });

    if (!penalty) {
      throw new NotFoundException("So‘z narxi topilmadi");
    }

    return penalty;
  }

  async findMine(userId: number) {
    return await this.penaltyRepo.find({
      where: {
        user: { id: userId },
      },
      order: { createdAt: "DESC" },
    });
  }

  async update(id: number, dto: UpdatePenaltyDto) {
    const penalty = await this.findOne(id);

    if (dto.userId !== undefined) {
      const user = await this.findManagerUser(dto.userId);
      penalty.user = user;
    }

    if (dto.amount !== undefined) penalty.amount = dto.amount;
    if (dto.reason !== undefined) penalty.reason = dto.reason;
    if (dto.reasonType !== undefined) penalty.reasonType = dto.reasonType;
    if (dto.penaltyDate !== undefined) penalty.penaltyDate = dto.penaltyDate;
    if (dto.status !== undefined) penalty.status = dto.status;
    if (dto.autoGenerated !== undefined) {
      penalty.autoGenerated = dto.autoGenerated;
    }
    if (dto.adminComment !== undefined) {
      penalty.adminComment = dto.adminComment ?? null;
    }

    return await this.penaltyRepo.save(penalty);
  }

  async remove(id: number) {
    const penalty = await this.findOne(id);
    await this.penaltyRepo.delete(id);

    return {
      message: "So‘z narxi o‘chirildi",
      data: penalty,
    };
  }
}